# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sidebar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2145, 846)
        MainWindow.setStyleSheet("*{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    background:transparent;\n"
"    padding:0;\n"
"    margin:0;\n"
"    color:#fff;\n"
"}\n"
"\n"
"#top_menu_widget, #icon_only_widget, #full_menu_widget{\n"
"    background-color:#16191d;\n"
"    border-radius: 25px;\n"
"    \n"
"    \n"
"}\n"
"#centralwidget{\n"
"    background-color:#1f232a;\n"
"}\n"
"\n"
"\n"
".QPushButton:hover{\n"
"    \n"
"    background-color:#1f235b;\n"
"    \n"
"}\n"
".QPushButton:checked{\n"
"    background-color:#1f235b;\n"
"}\n"
"#textInput{\n"
"    border-bottom:solid;\n"
"    border-width: 1px;\n"
"    border-color: #42474f;\n"
"}\n"
"#statusBar{\n"
"background-color:#16191d;\n"
"}\n"
"\n"
"#top_menu_widget{\n"
"    border-radius:10px;\n"
"}\n"
"#profile_widget{\n"
"    background-color:#16191d;\n"
"    border-radius:25px;\n"
"}\n"
"\n"
"QComboBox{\n"
"    background-color:rgb(44, 44, 44)\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon_only_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 10)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.icon_only_widget)
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/icons/logo.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.homeBtn = QtWidgets.QPushButton(self.icon_only_widget)
        self.homeBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeBtn.setIcon(icon)
        self.homeBtn.setIconSize(QtCore.QSize(24, 24))
        self.homeBtn.setCheckable(True)
        self.homeBtn.setChecked(True)
        self.homeBtn.setAutoExclusive(True)
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout.addWidget(self.homeBtn)
        self.mapsBtn = QtWidgets.QPushButton(self.icon_only_widget)
        self.mapsBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/map.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mapsBtn.setIcon(icon1)
        self.mapsBtn.setIconSize(QtCore.QSize(24, 24))
        self.mapsBtn.setCheckable(True)
        self.mapsBtn.setChecked(False)
        self.mapsBtn.setAutoExclusive(True)
        self.mapsBtn.setDefault(False)
        self.mapsBtn.setObjectName("mapsBtn")
        self.verticalLayout.addWidget(self.mapsBtn)
        self.terminalBtn = QtWidgets.QPushButton(self.icon_only_widget)
        self.terminalBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/terminal.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.terminalBtn.setIcon(icon2)
        self.terminalBtn.setIconSize(QtCore.QSize(24, 24))
        self.terminalBtn.setCheckable(True)
        self.terminalBtn.setAutoExclusive(True)
        self.terminalBtn.setObjectName("terminalBtn")
        self.verticalLayout.addWidget(self.terminalBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 235, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.settingsBtn = QtWidgets.QPushButton(self.icon_only_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.settingsBtn.setFont(font)
        self.settingsBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsBtn.setIcon(icon3)
        self.settingsBtn.setIconSize(QtCore.QSize(24, 24))
        self.settingsBtn.setCheckable(True)
        self.settingsBtn.setAutoExclusive(True)
        self.settingsBtn.setObjectName("settingsBtn")
        self.verticalLayout.addWidget(self.settingsBtn)
        self.infoBtn = QtWidgets.QPushButton(self.icon_only_widget)
        self.infoBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.infoBtn.setIcon(icon4)
        self.infoBtn.setIconSize(QtCore.QSize(24, 24))
        self.infoBtn.setCheckable(True)
        self.infoBtn.setAutoExclusive(True)
        self.infoBtn.setObjectName("infoBtn")
        self.verticalLayout.addWidget(self.infoBtn)
        self.helpBtn = QtWidgets.QPushButton(self.icon_only_widget)
        self.helpBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/help-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpBtn.setIcon(icon5)
        self.helpBtn.setIconSize(QtCore.QSize(24, 24))
        self.helpBtn.setCheckable(True)
        self.helpBtn.setAutoExclusive(True)
        self.helpBtn.setObjectName("helpBtn")
        self.verticalLayout.addWidget(self.helpBtn)
        self.horizontalLayout.addWidget(self.icon_only_widget, 0, QtCore.Qt.AlignLeft)
        self.full_menu_widget = QtWidgets.QWidget(self.centralwidget)
        self.full_menu_widget.setObjectName("full_menu_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.full_menu_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.full_menu_widget)
        self.label_2.setMaximumSize(QtCore.QSize(100, 100))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/icons/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.full_menu_widget)
        font = QtGui.QFont()
        font.setFamily("Pirulen Rg")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.homeBtn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.homeBtn_2.setFont(font)
        self.homeBtn_2.setIcon(icon)
        self.homeBtn_2.setIconSize(QtCore.QSize(24, 24))
        self.homeBtn_2.setCheckable(True)
        self.homeBtn_2.setChecked(True)
        self.homeBtn_2.setAutoExclusive(True)
        self.homeBtn_2.setObjectName("homeBtn_2")
        self.verticalLayout_2.addWidget(self.homeBtn_2)
        self.mapsBtn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mapsBtn_2.setFont(font)
        self.mapsBtn_2.setIcon(icon1)
        self.mapsBtn_2.setIconSize(QtCore.QSize(24, 24))
        self.mapsBtn_2.setCheckable(True)
        self.mapsBtn_2.setAutoExclusive(True)
        self.mapsBtn_2.setObjectName("mapsBtn_2")
        self.verticalLayout_2.addWidget(self.mapsBtn_2)
        self.terminalBtn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.terminalBtn_2.setFont(font)
        self.terminalBtn_2.setIcon(icon2)
        self.terminalBtn_2.setIconSize(QtCore.QSize(24, 24))
        self.terminalBtn_2.setCheckable(True)
        self.terminalBtn_2.setAutoExclusive(True)
        self.terminalBtn_2.setObjectName("terminalBtn_2")
        self.verticalLayout_2.addWidget(self.terminalBtn_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 297, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.settingsBtn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.settingsBtn_2.setFont(font)
        self.settingsBtn_2.setIcon(icon3)
        self.settingsBtn_2.setIconSize(QtCore.QSize(24, 24))
        self.settingsBtn_2.setCheckable(True)
        self.settingsBtn_2.setAutoExclusive(True)
        self.settingsBtn_2.setObjectName("settingsBtn_2")
        self.verticalLayout_2.addWidget(self.settingsBtn_2)
        self.infoBtn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.infoBtn_2.setFont(font)
        self.infoBtn_2.setIcon(icon4)
        self.infoBtn_2.setIconSize(QtCore.QSize(24, 24))
        self.infoBtn_2.setCheckable(True)
        self.infoBtn_2.setAutoExclusive(True)
        self.infoBtn_2.setObjectName("infoBtn_2")
        self.verticalLayout_2.addWidget(self.infoBtn_2)
        self.helpBtn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.helpBtn_2.setFont(font)
        self.helpBtn_2.setIcon(icon5)
        self.helpBtn_2.setIconSize(QtCore.QSize(24, 24))
        self.helpBtn_2.setCheckable(True)
        self.helpBtn_2.setAutoExclusive(True)
        self.helpBtn_2.setObjectName("helpBtn_2")
        self.verticalLayout_2.addWidget(self.helpBtn_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addWidget(self.full_menu_widget, 0, QtCore.Qt.AlignLeft)
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_widget.sizePolicy().hasHeightForWidth())
        self.main_widget.setSizePolicy(sizePolicy)
        self.main_widget.setMinimumSize(QtCore.QSize(500, 500))
        self.main_widget.setObjectName("main_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.top_menu_widget = QtWidgets.QWidget(self.main_widget)
        self.top_menu_widget.setMinimumSize(QtCore.QSize(100, 0))
        self.top_menu_widget.setObjectName("top_menu_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.top_menu_widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menu_scrl = QtWidgets.QPushButton(self.top_menu_widget)
        self.menu_scrl.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_scrl.setIcon(icon6)
        self.menu_scrl.setIconSize(QtCore.QSize(24, 24))
        self.menu_scrl.setCheckable(True)
        self.menu_scrl.setAutoRepeat(False)
        self.menu_scrl.setAutoExclusive(False)
        self.menu_scrl.setObjectName("menu_scrl")
        self.horizontalLayout_4.addWidget(self.menu_scrl)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PortSelect = QtWidgets.QComboBox(self.top_menu_widget)
        self.PortSelect.setMinimumSize(QtCore.QSize(100, 0))
        self.PortSelect.setDuplicatesEnabled(False)
        self.PortSelect.setObjectName("PortSelect")
        self.horizontalLayout_3.addWidget(self.PortSelect)
        self.BaudRateSelect = QtWidgets.QComboBox(self.top_menu_widget)
        self.BaudRateSelect.setMinimumSize(QtCore.QSize(100, 0))
        self.BaudRateSelect.setSizeIncrement(QtCore.QSize(0, 0))
        self.BaudRateSelect.setObjectName("BaudRateSelect")
        self.horizontalLayout_3.addWidget(self.BaudRateSelect)
        self.Connection_Button = QtWidgets.QPushButton(self.top_menu_widget)
        self.Connection_Button.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/connection_img.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Connection_Button.setIcon(icon7)
        self.Connection_Button.setIconSize(QtCore.QSize(30, 30))
        self.Connection_Button.setObjectName("Connection_Button")
        self.horizontalLayout_3.addWidget(self.Connection_Button)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.profile_Btn = QtWidgets.QPushButton(self.top_menu_widget)
        self.profile_Btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile_Btn.setIcon(icon8)
        self.profile_Btn.setIconSize(QtCore.QSize(24, 24))
        self.profile_Btn.setCheckable(True)
        self.profile_Btn.setChecked(False)
        self.profile_Btn.setAutoExclusive(False)
        self.profile_Btn.setObjectName("profile_Btn")
        self.horizontalLayout_4.addWidget(self.profile_Btn)
        self.verticalLayout_4.addWidget(self.top_menu_widget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_widget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_6 = QtWidgets.QFrame(self.page)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.ADI_frame = QtWidgets.QFrame(self.frame_6)
        self.ADI_frame.setGeometry(QtCore.QRect(20, 10, 240, 240))
        self.ADI_frame.setStyleSheet("#ADI_frame{background-color: rgba(117, 117, 117, 200);\n"
"border-radius: 25px;}")
        self.ADI_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ADI_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ADI_frame.setObjectName("ADI_frame")
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setGeometry(QtCore.QRect(0, 319, 791, 381))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.console_home = QtWidgets.QTextBrowser(self.frame_8)
        self.console_home.setMouseTracking(False)
        self.console_home.setStyleSheet("#console_home{\n"
"background-color: rgb(8, 8, 8);\n"
"border:3px solid;\n"
"border-radius:10%;\n"
"border-color:rgb(61, 61, 61)\n"
"}\n"
"QScrollBar:vertical {\n"
"    \n"
"    background-color:transparent;\n"
"    background:transparent;\n"
"    border-radius:5%;\n"
"    width:10%\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.393, y1:0, x2:0.453, y2:1, stop:0 rgba(29, 40, 200, 255), stop:1 rgba(57, 57, 57, 255));\n"
"    border-radius:5%;\n"
"    \n"
"}\n"
"\n"
"")
        self.console_home.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.console_home.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.console_home.setTabChangesFocus(False)
        self.console_home.setOverwriteMode(False)
        self.console_home.setOpenExternalLinks(False)
        self.console_home.setObjectName("console_home")
        self.verticalLayout_8.addWidget(self.console_home)
        self.HSI_frame = QtWidgets.QFrame(self.frame_6)
        self.HSI_frame.setGeometry(QtCore.QRect(280, 10, 240, 240))
        self.HSI_frame.setStyleSheet("#HSI_frame{background-color: rgba(117, 117, 117, 200);\n"
"border-radius: 25px;}")
        self.HSI_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HSI_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HSI_frame.setObjectName("HSI_frame")
        self.SI_frame = QtWidgets.QFrame(self.frame_6)
        self.SI_frame.setGeometry(QtCore.QRect(540, 10, 240, 240))
        self.SI_frame.setStyleSheet("#SI_frame{background-color: rgba(117, 117, 117, 200);\n"
"border-radius: 25px;}")
        self.SI_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SI_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SI_frame.setObjectName("SI_frame")
        self.image_label = QtWidgets.QLabel(self.frame_6)
        self.image_label.setGeometry(QtCore.QRect(910, 80, 481, 511))
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.verticalLayout_7.addWidget(self.frame_6)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.console_terminal = QtWidgets.QTextBrowser(self.page_3)
        self.console_terminal.setStyleSheet("#console_terminal{\n"
"background-color: rgb(8, 8, 8);\n"
"border:3px solid;\n"
"border-radius:10%;\n"
"border-color:rgb(61, 61, 61)\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    \n"
"    background-color:transparent;\n"
"    background:transparent;\n"
"    border-radius:5%;\n"
"    width:10%\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.393, y1:0, x2:0.453, y2:1, stop:0 rgba(29, 40, 200, 255), stop:1 rgba(57, 57, 57, 255));\n"
"    border-radius:5%;\n"
"    \n"
"}\n"
"\n"
"")
        self.console_terminal.setObjectName("console_terminal")
        self.verticalLayout_9.addWidget(self.console_terminal)
        self.frame_9 = QtWidgets.QFrame(self.page_3)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(70, 70, 70);\n"
"border-radius:5%;\n"
"padding:3px")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(32767)
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(".QPushButton:checked{\n"
"    \n"
"    background-color: rgb(61, 61, 61);\n"
"}\n"
".QPushButton:hover{\n"
"    background-color: rgb(61, 61, 61);\n"
"    \n"
"    \n"
"}")
        self.pushButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/send.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon9)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setCheckable(False)
        self.pushButton.setChecked(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.verticalLayout_9.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.page_4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pageSettings = QtWidgets.QLabel(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageSettings.sizePolicy().hasHeightForWidth())
        self.pageSettings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pageSettings.setFont(font)
        self.pageSettings.setAlignment(QtCore.Qt.AlignCenter)
        self.pageSettings.setObjectName("pageSettings")
        self.horizontalLayout_9.addWidget(self.pageSettings)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.page_5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame = QtWidgets.QFrame(self.page_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(30, 20, 361, 201))
        self.frame_3.setStyleSheet("\n"
"background-color:rgba(20, 25, 29, 220);\n"
"border-radius: 25px;\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.frame_4.setStyleSheet("border-radius: 50%;\n"
"border:none;\n"
"border-image: url(:/icons/icons/photo_6046499524345706809_x.jpg);\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(133, 30, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Pirulen Rg")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(126, 45, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(120, 70, 191, 121))
        self.label_6.setObjectName("label_6")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(90, 270, 361, 201))
        self.frame_5.setStyleSheet("\n"
"background-color:rgba(20, 25, 29, 220);\n"
"border-radius: 25px;\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.frame_7.setStyleSheet("border-radius: 50%;\n"
"border:none;\n"
"border-image: url(:/icons/icons/photo_6046499524345706809_x.jpg);\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        self.label_10.setGeometry(QtCore.QRect(133, 30, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Pirulen Rg")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        self.label_11.setGeometry(QtCore.QRect(126, 45, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        self.label_12.setGeometry(QtCore.QRect(120, 70, 191, 121))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.frame_2)
        self.horizontalLayout_10.addWidget(self.frame)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.page_6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pageHelp = QtWidgets.QLabel(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageHelp.sizePolicy().hasHeightForWidth())
        self.pageHelp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pageHelp.setFont(font)
        self.pageHelp.setAlignment(QtCore.Qt.AlignCenter)
        self.pageHelp.setObjectName("pageHelp")
        self.horizontalLayout_11.addWidget(self.pageHelp)
        self.stackedWidget.addWidget(self.page_6)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pageMaps = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageMaps.sizePolicy().hasHeightForWidth())
        self.pageMaps.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pageMaps.setFont(font)
        self.pageMaps.setAlignment(QtCore.Qt.AlignCenter)
        self.pageMaps.setObjectName("pageMaps")
        self.horizontalLayout_7.addWidget(self.pageMaps)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_5.addWidget(self.stackedWidget)
        self.profile_widget = QtWidgets.QWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profile_widget.sizePolicy().hasHeightForWidth())
        self.profile_widget.setSizePolicy(sizePolicy)
        self.profile_widget.setMinimumSize(QtCore.QSize(200, 200))
        self.profile_widget.setObjectName("profile_widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.profile_widget)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_5.setSpacing(11)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.profile_Img = QtWidgets.QLabel(self.profile_widget)
        self.profile_Img.setMinimumSize(QtCore.QSize(20, 20))
        self.profile_Img.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.profile_Img.setFont(font)
        self.profile_Img.setStyleSheet("")
        self.profile_Img.setText("")
        self.profile_Img.setPixmap(QtGui.QPixmap(":/icons/icons/photo_6046499524345706809_x.jpg"))
        self.profile_Img.setScaledContents(True)
        self.profile_Img.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_Img.setWordWrap(False)
        self.profile_Img.setIndent(-1)
        self.profile_Img.setOpenExternalLinks(False)
        self.profile_Img.setObjectName("profile_Img")
        self.verticalLayout_5.addWidget(self.profile_Img, 0, QtCore.Qt.AlignHCenter)
        self.profile_Name = QtWidgets.QLabel(self.profile_widget)
        font = QtGui.QFont()
        font.setFamily("Pirulen Rg")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.profile_Name.setFont(font)
        self.profile_Name.setObjectName("profile_Name")
        self.verticalLayout_5.addWidget(self.profile_Name)
        self.profile_Youtube = QtWidgets.QPushButton(self.profile_widget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/youtube.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile_Youtube.setIcon(icon10)
        self.profile_Youtube.setObjectName("profile_Youtube")
        self.verticalLayout_5.addWidget(self.profile_Youtube)
        self.profile_Instagram = QtWidgets.QPushButton(self.profile_widget)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/instagram.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile_Instagram.setIcon(icon11)
        self.profile_Instagram.setObjectName("profile_Instagram")
        self.verticalLayout_5.addWidget(self.profile_Instagram)
        self.profile_Github = QtWidgets.QPushButton(self.profile_widget)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/github.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile_Github.setIcon(icon12)
        self.profile_Github.setObjectName("profile_Github")
        self.verticalLayout_5.addWidget(self.profile_Github)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.horizontalLayout_5.addWidget(self.profile_widget)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addWidget(self.main_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.menu_scrl.toggled['bool'].connect(self.icon_only_widget.setVisible) # type: ignore
        self.menu_scrl.toggled['bool'].connect(self.full_menu_widget.setHidden) # type: ignore
        self.homeBtn.toggled['bool'].connect(self.homeBtn_2.setChecked) # type: ignore
        self.mapsBtn.toggled['bool'].connect(self.mapsBtn_2.setChecked) # type: ignore
        self.terminalBtn.toggled['bool'].connect(self.terminalBtn_2.setChecked) # type: ignore
        self.homeBtn_2.toggled['bool'].connect(self.homeBtn.setChecked) # type: ignore
        self.mapsBtn_2.toggled['bool'].connect(self.mapsBtn.setChecked) # type: ignore
        self.terminalBtn_2.toggled['bool'].connect(self.terminalBtn.setChecked) # type: ignore
        self.settingsBtn.toggled['bool'].connect(self.settingsBtn_2.setChecked) # type: ignore
        self.settingsBtn_2.toggled['bool'].connect(self.settingsBtn.setChecked) # type: ignore
        self.infoBtn.toggled['bool'].connect(self.infoBtn_2.setChecked) # type: ignore
        self.infoBtn_2.toggled['bool'].connect(self.infoBtn.setChecked) # type: ignore
        self.helpBtn.toggled['bool'].connect(self.helpBtn_2.setChecked) # type: ignore
        self.helpBtn_2.toggled['bool'].connect(self.helpBtn.setChecked) # type: ignore
        self.profile_Btn.toggled['bool'].connect(self.profile_widget.setVisible) # type: ignore
        self.profile_Btn.toggled['bool'].connect(self.profile_widget.setHidden) # type: ignore
        self.pushButton.toggled['bool'].connect(self.lineEdit.clear) # type: ignore
        self.pushButton.pressed.connect(self.lineEdit.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.homeBtn.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.mapsBtn.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.terminalBtn.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.settingsBtn.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.infoBtn.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.helpBtn.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.label_3.setText(_translate("MainWindow", "GRAVITEAM"))
        self.homeBtn_2.setText(_translate("MainWindow", "Home"))
        self.homeBtn_2.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.mapsBtn_2.setText(_translate("MainWindow", "Maps"))
        self.mapsBtn_2.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.terminalBtn_2.setText(_translate("MainWindow", "Terminal"))
        self.terminalBtn_2.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.settingsBtn_2.setText(_translate("MainWindow", "Settings"))
        self.settingsBtn_2.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.infoBtn_2.setText(_translate("MainWindow", "İnformations"))
        self.infoBtn_2.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.helpBtn_2.setText(_translate("MainWindow", "Help"))
        self.helpBtn_2.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.console_home.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">kjdnbkdjfndkfjdnfkdjfndfkjdndkjnk<br />dflbdknfbldfbd<br />fbdfdfdbfdfbdkjdnbkdjfndkfjdnfkdjfndfkjdndkjnk<br />dflbdknfbldfbd<br />fbdfdfdbfdfbdkjdnbkdjfndkfjdnfkdjfndfkjdndkjnk<br />dflbdknfbldfbd<br />fbdfdfdbfdfbdkjdnbkdjfndkfjdnfkdjfndfkjdndkjnk<br />dflbdknfbldfbd<br />fbdfdfdbfdfbdkjdnbkdjfndkfjdnfkdjfndfkjdndkjnk<br />dflbdknfbldfbd<br />fbdfdfdbfdfbdkjdnbkdjfndkfjdnfkdjfndfkjdndkjnk<br />dflbdknfbldfbd<br />fbdfdfdbfdfbdkjdnbkdjfndkfjdnfkdjfndfkjdndkjnk<br />dflbdknfbldfbd<br />fbdfdfdbfdfbdkjdnbkdjfndkfjdnfkdjfndfkjdndkjnk<br />dflbdknfbldfbd<br />fbdfdfdbfdfbdkjdnbkdjfndkfjdnfkdjfndfkjdndkjnk<br />dflbdknfbldfbd<br />fbdfdfdbfdfbdkjdnbkdjfndkfjdnfkdjfndfkjdndkjnk<br />dflbdknfbldfbd<br />fbdfdfdbfdfbdkjdnbkdjfndkfjdnfkdjfndfkjdndkjnk<br />dflbdknfbldfbd<br />fbdfdfdbfdfbd</p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Command here..."))
        self.pushButton.setShortcut(_translate("MainWindow", "Return"))
        self.pageSettings.setText(_translate("MainWindow", "Settings"))
        self.label_4.setText(_translate("MainWindow", "Yunus emre tom"))
        self.label_5.setText(_translate("MainWindow", "Member"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2 TEKNOFEST Üyeliği</li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1 TEKNOFEST Takım Kaptanlığı</li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Yazılımcı</li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3B Tasarımcısı</li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">İHA Pilotu</li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">12.Sınıf Öğrencisi</li></ul></body></html>"))
        self.label_10.setText(_translate("MainWindow", "Yunus emre tom"))
        self.label_11.setText(_translate("MainWindow", "Member"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2 TEKNOFEST Üyeliği</li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1 TEKNOFEST Takım Kaptanlığı</li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Yazılımcı</li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3B Tasarımcısı</li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">İHA Pilotu</li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">12.Sınıf Öğrencisi</li></ul></body></html>"))
        self.pageHelp.setText(_translate("MainWindow", "Help"))
        self.pageMaps.setText(_translate("MainWindow", "Maps"))
        self.profile_Name.setText(_translate("MainWindow", "Yunus Emre Tom"))
        self.profile_Youtube.setText(_translate("MainWindow", "@yunusemretom"))
        self.profile_Instagram.setText(_translate("MainWindow", "@yunusemretom"))
        self.profile_Github.setText(_translate("MainWindow", "#yunusemretom"))
import resource_rc
