# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\splash.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 430)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(56, 58, 89);\n"
"    color:rgb(220,220,220);\n"
"    border-radius:10px;\n"
"\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.label_title = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_title.setGeometry(QtCore.QRect(0, 105, 671, 90))
        font = QtGui.QFont()
        font.setFamily("Pirulen Rg")
        font.setPointSize(34)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color:rgb(29, 132, 200)")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_2_description = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_2_description.setGeometry(QtCore.QRect(0, 184, 671, 21))
        font = QtGui.QFont()
        font.setFamily("Pirulen Rg")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2_description.setFont(font)
        self.label_2_description.setStyleSheet("color: rgb(84, 91, 103)")
        self.label_2_description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2_description.setObjectName("label_2_description")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(70, 270, 551, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgb(98, 114, 164);\n"
"    border-radius:10px;\n"
"    border-style:none;\n"
"    text-align:center;\n"
"    color:rgb(204, 204, 204);\n"
"\n"
"}\n"
"QProgressBar::chunk{\n"
"    background-color: qlineargradient(spread:pad, x1:0.01, y1:0.477273, x2:1, y2:0.722, stop:0 rgba(96, 77, 200, 255), stop:1 rgba(18, 137, 200, 255));\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_3_loading = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_3_loading.setGeometry(QtCore.QRect(0, 295, 681, 20))
        font = QtGui.QFont()
        font.setFamily("Pirulen Rg")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_3_loading.setFont(font)
        self.label_3_loading.setStyleSheet("color: rgb(84, 91, 103)")
        self.label_3_loading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3_loading.setObjectName("label_3_loading")
        self.label_4_created = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_4_created.setGeometry(QtCore.QRect(0, 379, 670, 31))
        font = QtGui.QFont()
        font.setFamily("Pirulen Rg")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_4_created.setFont(font)
        self.label_4_created.setStyleSheet("color: rgb(84, 91, 103)")
        self.label_4_created.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4_created.setObjectName("label_4_created")
        self.verticalLayout.addWidget(self.dropShadowFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Graviteam"))
        self.label_2_description.setText(_translate("MainWindow", "App Descreption"))
        self.label_3_loading.setText(_translate("MainWindow", "loading..."))
        self.label_4_created.setText(_translate("MainWindow", "<strong>Created</strong> by Graviteam"))
